name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties','**/build.gradle','**/settings.gradle') }}

      - name: Install SDK tools
        uses: android-actions/sdk-manager@v2
        with:
          api-levels: 33
          components: "platform-tools,build-tools;33.0.2,emulator,platforms;android-33,system-images;android-21;default;x86"
          build-tools: 33.0.2

      - name: Build (assemble)
        run: ./gradlew --no-daemon clean assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
