name: Android CI - build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    # Set ANDROID_SDK_ROOT using runner-provided env variable $RUNNER_TEMP
    env:
      ANDROID_SDK_ROOT: $RUNNER_TEMP/android-sdk
      ANDROID_HOME: $RUNNER_TEMP/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make gradlew executable (if present)
        if: runner.os == 'Linux'
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties','**/build.gradle*','**/settings.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Android SDK & AVD tools
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 33
          arch: x86_64
          target: default
          force-avd-creation: false
          emulator-options: -no-window -no-audio
          disable-linux-hw-accel: true
          # A small script run while the emulator is up.
          # We don't need to run tests here; just keep it minimal so the step succeeds.
          script: |
            echo "Emulator created (no tests to run)."
            sleep 1

      - name: Build with Gradle (assembleDebug)
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleDebug
        env:
          # pass the same runtime path to the Gradle step explicitly
          ANDROID_SDK_ROOT: $RUNNER_TEMP/android-sdk
          ANDROID_HOME: $RUNNER_TEMP/android-sdk

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk