name: Android CI - build APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    env:
      ANDROID_SDK_ROOT: ${{ runner.temp }}/android-sdk
      ANDROID_HOME: ${{ runner.temp }}/android-sdk

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Make gradlew executable
        run: |
          if [ -f ./gradlew ]; then chmod +x ./gradlew; fi

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties','**/build.gradle*','**/settings.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Install Android command line tools and SDK packages
        run: |
          set -euo pipefail
          mkdir -p "$ANDROID_SDK_ROOT"
          cd /tmp

          CLI_ZIP="commandlinetools-linux-9477386_latest.zip"
          wget -q "https://dl.google.com/android/repository/${CLI_ZIP}" -O cmdline-tools.zip

          unzip -q cmdline-tools.zip -d cmdline-tools-unpacked
          rm cmdline-tools.zip || true

          mkdir -p "$ANDROID_SDK_ROOT/cmdline-tools/latest"

          if [ -d cmdline-tools-unpacked/cmdline-tools ]; then
            mv cmdline-tools-unpacked/cmdline-tools/* "$ANDROID_SDK_ROOT/cmdline-tools/latest/" || true
          else
            mv cmdline-tools-unpacked/* "$ANDROID_SDK_ROOT/cmdline-tools/latest/" || true
          fi
          rm -rf cmdline-tools-unpacked || true

          export PATH="$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH"

          yes | sdkmanager --sdk_root="$ANDROID_SDK_ROOT" --licenses || true
          sdkmanager --sdk_root="$ANDROID_SDK_ROOT" "platform-tools" "platforms;android-33" "build-tools;33.0.2" "platforms;android-21"

      - name: Build with Gradle (assembleDebug)
        uses: gradle/gradle-build-action@v3
        with:
          arguments: assembleDebug
        env:
  ANDROID_SDK_ROOT: /usr/local/android-sdk
  ANDROID_HOME: /usr/local/android-sdk

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk