name: Unpack ZIP to Root

on:
  workflow_dispatch:
  push:
    paths:
      - 'ngomik.zip'

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Unpack ngomik.zip to root
        run: |
          unzip -o ngomik.zip -d .
